FROM testdocker-registry.web-site.com:5000/alpine:tzdata
COPY config/ /server/config/
ADD ./grpc-server /server/grpc-server
RUN  chmod u+x /server/grpc-server
WORKDIR /server
EXPOSE 50052
COPY run-grpc.sh /run-grpc.sh
RUN chmod u+x /run-grpc.sh
CMD ["/run-grpc.sh"]