mysql:
  test_platform:
    maxOpenConns: 50 #设置空闲连接池中的最大连接数
    maxIdleConns: 3 #设置空闲连接池中的最大连接数。
    maxLifetime: 240 #设置可重用连接的最长时间 0不限制
    debug: false
    charset: utf8mb4
    servers:
      - host: 172.16.0.3
        port: 3306
        db: bvt_api_test
        user: bvt_api_test
        passwd: 123456
