server:
  - name: user
    endpoint: 127.0.0.2:50003
    initialCap: 5    #初始连接数
    maxCap: 300      #最大连接数
    idleTimeout: 480 #在池子存活时间
  - name: goods
    #    endpoint: 127.0.0.1:60001 # 本地
    endpoint: 127.0.0.2:50100 # 本地
    initialCap: 5    #初始连接数
    maxCap: 100      #最大连接数
    idleTimeout: 300 #在池子存活时间
  - name: pay
    endpoint: 127.0.0.2:50015 # 本地
    initialCap: 5    #初始连接数
    maxCap: 100      #最大连接数
    idleTimeout: 300 #在池子存活时间

