redis:
  default:
    maxActive: 50 #最大的激活连接数,支持最高并发数
    maxIdle: 5  #最大的空闲连接数
    idleTimeout: 180 #最大的空闲连接等待时间，超过此时间后，空闲连接将被关闭
    servers:
      - address: 127.0.0.1:6379
        passwd: redispasswd123
        db: 0
  db1:
    maxActive: 50 #最大的激活连接数,支持最高并发数
    maxIdle: 5  #最大的空闲连接数
    idleTimeout: 180 #最大的空闲连接等待时间，超过此时间后，空闲连接将被关闭
    servers:
      - address: 127.0.0.1:6379
        passwd: redispasswd123
        db: 1